[tools]
bat = "latest"
btop = "latest"
delta = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
neovim = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
tmux = "latest"
yq = "latest"
