#!/usr/bin/env bash
# Customize these in the config file instead of editing them here.

# shellcheck disable=SC2034
declare -A DEFAULT_MISE_LANGUAGES

DEFAULT_MISE_LANGUAGES["node"]="node@24"
DEFAULT_MISE_LANGUAGES["python"]="python@3.14"
DEFAULT_MISE_LANGUAGES["go"]="go@latest"
DEFAULT_MISE_LANGUAGES["java"]="java@corretto-17"
